Repository NullVoxPopuli/ember-resources, pull requests merged in 2024-01, with the labels that each got.

#1069 Eslint plugin ember alpha v12 testing
  package.json
  pnpm-lock.yaml
  test-app/.eslintignore
  test-app/.eslintrc.js
  test-app/app/components/glint-gts.gts
  test-app/app/components/util/remote-data.gts
  test-app/tests/core/function-resource/clock-test.gts
  test-app/tests/core/function-resource/composition-test.gts
  test-app/tests/core/function-resource/rendering-test.gts
  test-app/tests/core/rendering-test.gts
  test-app/tests/modifier/rendering-test.gts
  test-app/tests/service/rendering-test.gts
  test-app/tests/utils/fps/rendering-test.gts
  test-app/tests/utils/function/rendering-test.gts
  test-app/tests/utils/function/timing-test.gts
  test-app/tests/utils/keep-latest/rendering-test.gts
  test-app/tests/utils/remote-data/rendering-test.gts
Labels: internal

#1051 Fix issue with keepLatest and empty values
  ember-resources/src/util/keep-latest.ts
  test-app/tests/utils/keep-latest/js-test.ts
  test-app/tests/utils/keep-latest/rendering-test.gts
Labels: bug

#1070 [v6]: Deprecate util/* imports
  ember-resources/src/util/debounce.ts
  ember-resources/src/util/ember-concurrency.ts
  ember-resources/src/util/fps.ts
  ember-resources/src/util/function.ts
  ember-resources/src/util/helper.ts
  ember-resources/src/util/keep-latest.ts
  ember-resources/src/util/map.ts
  ember-resources/src/util/remote-data.ts
Labels: enhancement

#1074 [v6]: Ensure that the available API for v7 does not throw deprecations
  pnpm-lock.yaml
  test-app-deprecations/.editorconfig
  test-app-deprecations/.ember-cli
  test-app-deprecations/.eslintignore
  test-app-deprecations/.eslintrc.js
  test-app-deprecations/.github/workflows/ci.yml
  test-app-deprecations/.gitignore
  test-app-deprecations/.prettierignore
  test-app-deprecations/.prettierrc.js
  test-app-deprecations/.stylelintignore
  test-app-deprecations/.stylelintrc.js
  test-app-deprecations/.template-lintrc.js
  test-app-deprecations/.watchmanconfig
  test-app-deprecations/README.md
  test-app-deprecations/app/app.js
  test-app-deprecations/app/components/.gitkeep
  test-app-deprecations/app/controllers/.gitkeep
  test-app-deprecations/app/helpers/.gitkeep
  test-app-deprecations/app/index.html
  test-app-deprecations/app/models/.gitkeep
  test-app-deprecations/app/router.js
  test-app-deprecations/app/routes/.gitkeep
  test-app-deprecations/app/styles/app.css
  test-app-deprecations/app/templates/application.hbs
  test-app-deprecations/config/deprecation-workflow.js
  test-app-deprecations/config/ember-cli-update.json
  test-app-deprecations/config/environment.js
  test-app-deprecations/config/optional-features.json
  test-app-deprecations/config/targets.js
  test-app-deprecations/ember-cli-build.js
  test-app-deprecations/package.json
  test-app-deprecations/public/robots.txt
  test-app-deprecations/testem.js
  test-app-deprecations/tests/index.html
  test-app-deprecations/tests/test-helper.js
  test-app-deprecations/tests/unit/no-deprecations-test.js
Labels: internal

#1076 Deprecate and move service and modifier to reactiveweb
  ember-resources/src/modifier/index.ts
  ember-resources/src/service.ts
Labels: enhancement

#1078 Update deprecation links
  ember-resources/src/modifier/index.ts
  ember-resources/src/service.ts
Labels: documentation

#1079 Add link to the v6 branch
  README.md
Labels: documentation

#1083 Remove service
  dev/estimate-bytes/index.js
  docs/typedoc.utils.config.json
  ember-resources/package.json
  ember-resources/src/service.ts
  test-app/tests/service/rendering-test.gts
Labels: breaking

#1082 Remove class-based Resource
  .github/actions/assert-build/action.yml
  ember-resources/src/core/class-based/index.ts
  ember-resources/src/core/class-based/manager.ts
  ember-resources/src/core/class-based/resource.ts
  ember-resources/src/core/index.ts
  ember-resources/src/index.ts
  ember-resources/type-tests/args-helpers.test.ts
  ember-resources/type-tests/class-resource.test.ts
  ember-resources/type-tests/from-thunk-inference.test.ts
  test-app/app/components/-resources.ts
  test-app/app/components/glint-colocated.hbs
  test-app/app/components/glint-colocated.ts
  test-app/app/components/glint-gts.gts
  test-app/tests/core/class-resource/js-test.ts
  test-app/tests/core/rendering-test.gts
  test-app/tests/type-tests/class-based.ts
Labels: breaking

#1084 Remove utils from API Reference docs (typedoc)
  dev/estimate-bytes/index.js
  docs/build.mjs
  docs/typedoc.utils.config.json
Labels: documentation

#1086 Remove API Reference docs' sidebar
  docs/typedoc.config.json
Labels: documentation

#1085 Remove link
  ember-resources/package.json
  ember-resources/src/link.ts
  ember-resources/type-tests/link.test.ts
  test-app/tests/link-test.ts
Labels: breaking

#1088 Remove deprecation testing app that was added in v6
  pnpm-workspace.yaml
  test-app-deprecations/.editorconfig
  test-app-deprecations/.ember-cli
  test-app-deprecations/.eslintignore
  test-app-deprecations/.eslintrc.js
  test-app-deprecations/.github/workflows/ci.yml
  test-app-deprecations/.gitignore
  test-app-deprecations/.prettierignore
  test-app-deprecations/.prettierrc.js
  test-app-deprecations/.stylelintignore
  test-app-deprecations/.stylelintrc.js
  test-app-deprecations/.template-lintrc.js
  test-app-deprecations/.watchmanconfig
  test-app-deprecations/README.md
  test-app-deprecations/app/app.js
  test-app-deprecations/app/components/.gitkeep
  test-app-deprecations/app/controllers/.gitkeep
  test-app-deprecations/app/helpers/.gitkeep
  test-app-deprecations/app/index.html
  test-app-deprecations/app/models/.gitkeep
  test-app-deprecations/app/router.js
  test-app-deprecations/app/routes/.gitkeep
  test-app-deprecations/app/styles/app.css
  test-app-deprecations/app/templates/application.hbs
  test-app-deprecations/config/deprecation-workflow.js
  test-app-deprecations/config/ember-cli-update.json
  test-app-deprecations/config/environment.js
  test-app-deprecations/config/optional-features.json
  test-app-deprecations/config/targets.js
  test-app-deprecations/ember-cli-build.js
  test-app-deprecations/package.json
  test-app-deprecations/public/robots.txt
  test-app-deprecations/testem.js
  test-app-deprecations/tests/index.html
  test-app-deprecations/tests/test-helper.js
  test-app-deprecations/tests/unit/no-deprecations-test.js
Labels: internal

#1089 Ensure every supported version of Ember has no deprecations triggered from ember-resources' usage.
  pnpm-lock.yaml
  test-app/config/deprecation-workflow.js
  test-app/package.json
Labels: enhancement

#1090 Remove the 'core' import, only allowing importing from 'ember-resources'
  .github/actions/assert-build/action.yml
  ember-resources/package.json
  ember-resources/src/cell.ts
  ember-resources/src/core/index.ts
  ember-resources/src/function-based/immediate-invocation.ts
  ember-resources/src/function-based/index.ts
  ember-resources/src/function-based/manager.ts
  ember-resources/src/function-based/resource.ts
  ember-resources/src/function-based/types.ts
  ember-resources/src/function-based/utils.ts
  ember-resources/src/index.ts
  ember-resources/src/types.ts
  ember-resources/src/types/base.ts
  ember-resources/src/types/signature-args.ts
  ember-resources/src/types/thunk.ts
  ember-resources/src/use.ts
  ember-resources/src/utils.ts
  ember-resources/tsconfig.json
Labels: breaking

#1092 Setup release automation for v6
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  .github/workflows/push-dist.yml
  .github/workflows/weekly-typescript.yml
Labels: internal

#1094 Fix declaration output
  ember-resources/package.json
  pnpm-lock.yaml
Labels: bug

#1091 Implement custom usables, `regusterUsable`
  dev/estimate-bytes/index.js
  ember-resources/src/function-based/resource.ts
  ember-resources/src/index.ts
  ember-resources/src/types.ts
  ember-resources/src/types/base.ts
  ember-resources/src/types/thunk.ts
  ember-resources/src/use.ts
  ember-resources/src/utils.ts
  ember-resources/type-tests/thunk-helpers.test.ts
  test-app/tests/type-tests/types.ts
  test-app/tests/unit/registerUsable-test.ts
  test-app/types/glint-registry.d.ts
  test-app/types/index.d.ts
Labels: enhancement

#1095 Support ember-source 5.4
  .github/workflows/ci.yml
  test-app/config/ember-try.js
Labels: enhancement

#1096 Drop unused dependencies and widen peers further
  ember-resources/package.json
  pnpm-lock.yaml
Labels: enhancement

#1098 Remove unused type utils
  ember-resources/src/types.ts
  ember-resources/src/types/base.ts
  ember-resources/src/types/signature-args.ts
  ember-resources/type-tests/args-helpers.test.ts
  ember-resources/type-tests/core-types.test.ts
Labels: internal

#1099 Test against (and add support for) TypeScript 5.3
  .github/workflows/ci.yml
Labels: enhancement, internal

#1100 Require ember-cli-app-consumers have at least ember-cli-babel 8.2
  pnpm-lock.yaml
  test-app/package.json
Labels: breaking

#1102 Fix API Reference docs by moving from Cloudflare to Vercel
  .github/workflows/ci.yml
Labels: documentation

#1101 Require an owner to exist to be wired through to the resource.
  ember-resources/src/function-based/immediate-invocation.ts
  ember-resources/src/function-based/manager.ts
  test-app/tests/core/function-resource/clock-test.gts
  test-app/tests/core/function-resource/js-test.ts
  test-app/tests/core/function-resource/js-use-test.gts
  test-app/tests/core/function-resource/rendering-test.gts
Labels: bug, breaking

#1104 Remove MSW
  package.json
  pnpm-lock.yaml
  test-app/package.json
  test-app/public/mockServiceWorker.js
  test-app/tests/msw.ts
Labels: internal

#1106 Use fix for release-plan from: https://github.com/ef4/lerna-changelog/pull/8
  package.json
  pnpm-lock.yaml
Labels: internal

#1108 Update release-plan for https://github.com/embroider-build/release-plan/pull/47
  package.json
  pnpm-lock.yaml
Labels: dependencies

#1107 Move recommendation of resourceFactory to better align with how TypeScript works
  DOCS.md
  docs/docs/ember.md
  docs/docs/resources.md
  ember-resources/src/function-based/immediate-invocation.ts
  ember-resources/src/type-tests/use.test.ts
Labels: documentation

#1115 Update migrations for 7.0
  MIGRATIONS.md
Labels: documentation
